PollSite_1/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url('', include('polls.urls', namespace="polls")),
   	url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
)

PollSite_2/PollSite_2/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from polls import views
admin.autodiscover()

urlpatterns = patterns('',
	url('', include('polls.urls', namespace="polls")),
	url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
)

PollSite_2/polls/urls.py
from django.conf.urls import patterns, url
from polls import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^(?P<poll_id>\d+)/$', views.detail, name='detail'),
	url(r'^(?P<poll_id>\d+)/results/$', views.results, name='results'),
	url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
)

PollSite_3/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url('', include('polls.urls', namespace='polls')),
	url(r'^poll/', include('polls.urls', namespace='polls')),
    url(r'^admin/', include(admin.site.urls)),
)

PollSite_4/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'PollSite_4.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

polls/urls.py
from django.conf.urls import patterns, url
from polls import views

urlpatterns = patterns('',
	url(r'^$', views.IndexView.as_view(), name="index"),
	url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name="details"),
	url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name="results"),
	url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name="vote"),
)

PollSite_2/polls/models.py
import datetime
from django.db import models
from django.utils import timezone

class Poll(models.Model):
	question = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')

	def __unicode__(self):
		return self.question

	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now

	was_published_recently.short_description = "Recently Published?"
	was_published_recently.boolean = True

class Choice(models.Model):
	poll = models.ForeignKey(Poll)
	text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __unicode__(self):
		return self.text

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

class Poll(models.Model):
	question = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	
	def __unicode__(self):
		return self.question
		
	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now

	was_published_recently.admin_order_field = "pub_date"
	was_published_recently.boolean = True
	was_published_recently.short_description = "Published Recently?"
	
class Choice(models.Model):
	poll = models.ForeignKey(Poll)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	
	def __unicode__(self):
		return self.choice_text

PollSite_2/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.views import generic
from polls.models import Poll

# class DetailView(generic.DetailView):
# 	model = Poll
# 	template_name = 'polls/detail.html'

def index(request):
	latest_polls = Poll.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
	context = {'latest_polls': latest_polls}
	return render(request, 'polls/index.html', context)

def detail(request, poll_id):
	poll = get_object_or_404(Poll, pk=poll_id)
	if poll.pub_date > timezone.now():
		raise Http404
	else:
		context = {'poll': poll}
		return render(request, 'polls/detail.html', context)

def results(request, poll_id):
	poll = get_object_or_404(Poll, pk=poll_id)
	context = {'poll': poll}
	return render(request, 'polls/result.html', context)

def vote(request, poll_id):
	poll = get_object_or_404(Poll, pk=poll_id)
	try:
		choice = poll.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		context = {'poll':poll, 'error_message':'You didn\'t choose anything!'}
		return render(request, 'poll/detail.html', context)
	else:
		choice.votes += 1
		choice.save()
		return HttpResponseRedirect(reverse('polls:results', args=(poll_id)))

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from polls.models import Poll, Choice

# def index(request):
# 	latest_poll_list = Poll.objects.order_by('-pub_date')[:5]
# 	context = {'latest_poll_list': latest_poll_list}
# 	return render(request, 'polls/index.html', context)

# def details(request, poll_id):
# 	poll = get_object_or_404(Poll, id=poll_id)
# 	return render(request, 'polls/detail.html', {'poll': poll})

# def results(request, poll_id):
# 	poll = get_object_or_404(Poll, id=poll_id)
# 	return render(request, 'polls/result.html', {'poll': poll})

class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'latest_poll_list'

	def get_queryset(self):
		""""Return latest 5 polls"""
		return Poll.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
		
class DetailView(generic.DetailView):
	model = Poll
	template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
	model = Poll
	template_name = 'polls/result.html'

def vote(request, poll_id):
	poll = get_object_or_404(Poll, id=poll_id)

	try:
		choice = poll.choice_set.get(id=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'polls/detail.html', {'poll':poll, 'error_message':"No choice was selected."})
	else:
		choice.votes += 1
		choice.save()
		return HttpResponseRedirect(reverse('polls:results', args=(poll.id,)))

PollSite_2/polls/templates/polls/detail.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}">

{{poll.question}}

{% if error_message %}
	<p style="color:red">{{error_message}}</p>
{% endif %}

<form action="{% url 'polls:vote' poll.id %}" method="POST">
	{% csrf_token %}
	{% for choice in poll.choice_set.all %}
		<input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
		<label for="choice{{forloop.counter}}">{{choice.text}}</label>
	{% endfor %}
	<input type="submit" value="Vote!">
</form>

PollSite_2/polls/templates/polls/index.html
<h1>Latest Polls</h1>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}" />

{% if latest_polls %}
	<ul>
	{% for poll in latest_polls %}
		<li><a href="{% url 'polls:detail' poll.id %}">{{poll.question}}</li>
	{% endfor %}
	</ul>
{% else %}
	<p>No latest poll</p>
{% endif %}

PollSite_2/polls/templates/polls/result.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}">

{{poll.question}}

<ul>
{% for choice in poll.choice_set.all %}
	<li>{{choice.text}} --> {{choice.votes}} vote{{ choice.votes|pluralize}}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' poll.id %}">Vote again?</a>

polls/templates/polls/detail.html
<h1>{{ poll.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' poll.id %}" method="post">
	{% csrf_token %}

	{% for choice in poll.choice_set.all %}
		<input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}" />
		<label for="choice{{forloop.counter}}">{{choice.choice_text}}</label>
	{% endfor %}

	<input type="submit" value="Vote!" />
</form>

polls/templates/polls/details.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}">

<h1>{{poll.question}}</h1>

{% if error_message %}
	<p style="color:red">{{error_message}}</p>
{% endif %}

<form action="{% url 'polls:vote' poll.id %}" method="POST">
{% csrf_token %}
	{% for choice in poll.choice_set.all %}
		<input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}" />
		<label for="choice{{forloop.counter}}">{{choice.text}}</label>
		</br>
	{% endfor %}
	<input type="submit" value="Vote!" />
</form>

<a href="{% url 'polls:index' %}">Home</a>

polls/templates/polls/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_poll_list %}
	<ul>
	{% for poll in latest_poll_list %}
		<li><a href="{% url 'polls:details' poll.id %}">{{poll.question}}</li>
	{% endfor %}
	</ul>
{% else %}
	<p>No polls available.</p>
{% endif %}

polls/templates/polls/result.html
<h1>{{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
	<li>{{ choice.choice_text }} -> {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:details' poll.id %}">Vote again?</a>

polls/templates/polls/results.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}">

<h1>{{poll.question}}</h1>

<ul>
{% for choice in poll.choice_set.all %}
	<li>{{choice.text}} --> {{choice.vote_count}} vote{{choice.vote_count|pluralize}}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:details' poll.id %}">Back to Poll</a>